trigger:
  - main  # Runs when changes are pushed to 'main' branch

pool:
  name: Default  # Uses your self-hosted agent

steps:
  - script: |
      python -m venv venv
      call venv\Scripts\activate  # For Windows
      pip install -r requirements.txt
    displayName: "Set up Python Virtual Environment & Install Dependencies"
    condition: succeededOrFailed()

  - script: |
      call venv\Scripts\activate  # Activating virtual environment
      pabot --processes 2 --output output.xml --report report.html --log log.html --variable browserName:MicrosoftEdge --variable version:latest --variable ROBOT_BROWSER:Edge .
    displayName: "Run All Robot Tests with Pabot (Parallel Execution)"
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/output.xml'
      mergeTestResults: true
      testRunTitle: "Robot Framework Tests"
    condition: always()
    displayName: "Publish Test Results"
